--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Terpz710/EnchantmentShopUI
build-by-default: true
branches:
- main
projects:
  EnchantmentShopUI:
    path: ""
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
    libs:
      - src: David-pm-pl/libEco/libEco
        version: ^3.0.0
        branch: stable
...
